name: molecular_simulations
channels:
  - conda-forge
dependencies:
  - mdtraj
  - numba
  - openbabel
  - openmm
  - parmed
  - parsl
  - pdbfixer
  - polars
  - pydantic
  - python=3.12
  - pyyaml
  - rdkit
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx-rtd-theme
